

CREATE TABLE secrets (
    id SERIAL PRIMARY KEY AUTOINCREMENT,
    token VARCHAR(255) NOT NULL,
    text TEXT,
    password VARCHAR(255),
    expiration_date TIMESTAMP NOT NULL,
    is_burned BOOLEAN NOT NULL DEFAULT FALSE,
    is_viewed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
