// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package repository

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.checkSecretExpirationStmt, err = db.PrepareContext(ctx, checkSecretExpiration); err != nil {
		return nil, fmt.Errorf("error preparing query CheckSecretExpiration: %w", err)
	}
	if q.createSecretStmt, err = db.PrepareContext(ctx, createSecret); err != nil {
		return nil, fmt.Errorf("error preparing query CreateSecret: %w", err)
	}
	if q.deleteSecretByTokenStmt, err = db.PrepareContext(ctx, deleteSecretByToken); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSecretByToken: %w", err)
	}
	if q.getSecretByTokenStmt, err = db.PrepareContext(ctx, getSecretByToken); err != nil {
		return nil, fmt.Errorf("error preparing query GetSecretByToken: %w", err)
	}
	if q.listAllSecretsStmt, err = db.PrepareContext(ctx, listAllSecrets); err != nil {
		return nil, fmt.Errorf("error preparing query ListAllSecrets: %w", err)
	}
	if q.markSecretAsBurnedStmt, err = db.PrepareContext(ctx, markSecretAsBurned); err != nil {
		return nil, fmt.Errorf("error preparing query MarkSecretAsBurned: %w", err)
	}
	if q.markSecretAsViewedStmt, err = db.PrepareContext(ctx, markSecretAsViewed); err != nil {
		return nil, fmt.Errorf("error preparing query MarkSecretAsViewed: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.checkSecretExpirationStmt != nil {
		if cerr := q.checkSecretExpirationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing checkSecretExpirationStmt: %w", cerr)
		}
	}
	if q.createSecretStmt != nil {
		if cerr := q.createSecretStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createSecretStmt: %w", cerr)
		}
	}
	if q.deleteSecretByTokenStmt != nil {
		if cerr := q.deleteSecretByTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSecretByTokenStmt: %w", cerr)
		}
	}
	if q.getSecretByTokenStmt != nil {
		if cerr := q.getSecretByTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSecretByTokenStmt: %w", cerr)
		}
	}
	if q.listAllSecretsStmt != nil {
		if cerr := q.listAllSecretsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAllSecretsStmt: %w", cerr)
		}
	}
	if q.markSecretAsBurnedStmt != nil {
		if cerr := q.markSecretAsBurnedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markSecretAsBurnedStmt: %w", cerr)
		}
	}
	if q.markSecretAsViewedStmt != nil {
		if cerr := q.markSecretAsViewedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markSecretAsViewedStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                        DBTX
	tx                        *sql.Tx
	checkSecretExpirationStmt *sql.Stmt
	createSecretStmt          *sql.Stmt
	deleteSecretByTokenStmt   *sql.Stmt
	getSecretByTokenStmt      *sql.Stmt
	listAllSecretsStmt        *sql.Stmt
	markSecretAsBurnedStmt    *sql.Stmt
	markSecretAsViewedStmt    *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                        tx,
		tx:                        tx,
		checkSecretExpirationStmt: q.checkSecretExpirationStmt,
		createSecretStmt:          q.createSecretStmt,
		deleteSecretByTokenStmt:   q.deleteSecretByTokenStmt,
		getSecretByTokenStmt:      q.getSecretByTokenStmt,
		listAllSecretsStmt:        q.listAllSecretsStmt,
		markSecretAsBurnedStmt:    q.markSecretAsBurnedStmt,
		markSecretAsViewedStmt:    q.markSecretAsViewedStmt,
	}
}
