// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package repository

import (
	"database/sql"
	"time"
)

type Secret struct {
	ID             interface{}
	Token          string
	Text           sql.NullString
	Password       sql.NullString
	ExpirationDate time.Time
	IsBurned       bool
	IsViewed       bool
	CreatedAt      time.Time
}
