// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: secrets_query.sql

package repository

import (
	"context"
	"database/sql"
	"time"
)

const checkSecretExpiration = `-- name: CheckSecretExpiration :one
SELECT COUNT(*) > 0 AS has_been_purged
FROM secrets
WHERE token = ? AND expiration_date < NOW()
`

// Checks if a secret with the given token has expired
func (q *Queries) CheckSecretExpiration(ctx context.Context, token string) (bool, error) {
	row := q.queryRow(ctx, q.checkSecretExpirationStmt, checkSecretExpiration, token)
	var has_been_purged bool
	err := row.Scan(&has_been_purged)
	return has_been_purged, err
}

const createSecret = `-- name: CreateSecret :execresult
INSERT INTO secrets (
    token,
    text,
    password,
    expiration_date
) VALUES (
    ?,
    ?,
    ?,
    ?
)
`

type CreateSecretParams struct {
	Token          string
	Text           sql.NullString
	Password       sql.NullString
	ExpirationDate time.Time
}

// Inserts a new secret into the table and returns the ID of the newly inserted row
func (q *Queries) CreateSecret(ctx context.Context, arg CreateSecretParams) (sql.Result, error) {
	return q.exec(ctx, q.createSecretStmt, createSecret,
		arg.Token,
		arg.Text,
		arg.Password,
		arg.ExpirationDate,
	)
}

const deleteSecretByToken = `-- name: DeleteSecretByToken :execresult
DELETE FROM secrets
WHERE token = ?
`

// Deletes a secret from the table based on the token
func (q *Queries) DeleteSecretByToken(ctx context.Context, token string) (sql.Result, error) {
	return q.exec(ctx, q.deleteSecretByTokenStmt, deleteSecretByToken, token)
}

const getSecretByToken = `-- name: GetSecretByToken :one
SELECT id, token, text, password, expiration_date, is_burned, is_viewed, created_at FROM secrets
WHERE token = ?
`

// Retrieves a single secret from the table based on the token
func (q *Queries) GetSecretByToken(ctx context.Context, token string) (Secret, error) {
	row := q.queryRow(ctx, q.getSecretByTokenStmt, getSecretByToken, token)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.Text,
		&i.Password,
		&i.ExpirationDate,
		&i.IsBurned,
		&i.IsViewed,
		&i.CreatedAt,
	)
	return i, err
}

const listAllSecrets = `-- name: ListAllSecrets :many
SELECT id, token, text, password, expiration_date, is_burned, is_viewed, created_at FROM secrets
`

// Lists all secrets in the table
func (q *Queries) ListAllSecrets(ctx context.Context) ([]Secret, error) {
	rows, err := q.query(ctx, q.listAllSecretsStmt, listAllSecrets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Secret
	for rows.Next() {
		var i Secret
		if err := rows.Scan(
			&i.ID,
			&i.Token,
			&i.Text,
			&i.Password,
			&i.ExpirationDate,
			&i.IsBurned,
			&i.IsViewed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSecretAsBurned = `-- name: MarkSecretAsBurned :execresult
UPDATE secrets
SET is_burned = TRUE
WHERE token = ?
`

// Marks a secret as burned by setting is_burned to TRUE for the given token
func (q *Queries) MarkSecretAsBurned(ctx context.Context, token string) (sql.Result, error) {
	return q.exec(ctx, q.markSecretAsBurnedStmt, markSecretAsBurned, token)
}

const markSecretAsViewed = `-- name: MarkSecretAsViewed :execresult
UPDATE secrets
SET is_viewed = TRUE
WHERE token = ?
`

// Marks a secret as viewed by setting is_viewed to TRUE for the given token
func (q *Queries) MarkSecretAsViewed(ctx context.Context, token string) (sql.Result, error) {
	return q.exec(ctx, q.markSecretAsViewedStmt, markSecretAsViewed, token)
}
